# Sua chave na OpenAI
OPENAI_API_KEY = "sk-..."

# URL da API do Astra e Token
ASTRA_DB_VECTOR_API_ENDPOINT = "https://<...>.apps.astra.datastax.com"
ASTRA_DB_VECTOR_TOKEN = "AstraCS:<...>"

[passwords]
datastax = "astra"

[languages]
datastax = "pt_BR"

[delete_option]
datastax = "True"

